export enum SHIPMENT_METHOD {
  PICKUP = 0,
  DELIVERY = 1,
}
export const SHIPMENT_METHOD_NAMES = {
  [SHIPMENT_METHOD.PICKUP]: "Pick Up",
  [SHIPMENT_METHOD.DELIVERY]: "Delivery",
};
export enum ORDER_STATUS {
  PENDING = 0,
  CONFIRMED = 1,
  DELIVERING = 2,
  DELIVERED = 3,
  CANCELLED = 4,
  REFUNDING = 5,
  REFUNDED = 6,
  SUCCEEDED = 7,
  SETTLED = 8,
  WAITING_FOR_PAYMENT = 9,
  REJECTED = 10,
  EXPIRED = 11,
  ON_GOING = 12,
  COMPLETED = 13,
  USER_PICKED_UP = 14,
  PREPARED = 15,
  PAID = 16,
  REFUND_REJECTED = 17
}
export const ON_GOING_ORDER_STATUS = [
  ORDER_STATUS.PENDING,
  ORDER_STATUS.CONFIRMED,
  ORDER_STATUS.DELIVERING,
  ORDER_STATUS.REFUNDING,
  ORDER_STATUS.WAITING_FOR_PAYMENT,
  ORDER_STATUS.ON_GOING,
];
export const ORDER_STATUS_NAMES = {
  [ORDER_STATUS.PENDING]: "Pending",
  [ORDER_STATUS.CONFIRMED]: "Confirm",
  [ORDER_STATUS.DELIVERING]: "Delivering",
  [ORDER_STATUS.DELIVERED]: "Delivered",
  [ORDER_STATUS.CANCELLED]: "Cancel",
  [ORDER_STATUS.REFUNDING]: "Refunding",
  [ORDER_STATUS.REFUNDED]: "Refunded",
  [ORDER_STATUS.SUCCEEDED]: "Succeeded",
  [ORDER_STATUS.SETTLED]: "Setteld",
  [ORDER_STATUS.WAITING_FOR_PAYMENT]: "Waiting for payment",
  [ORDER_STATUS.REJECTED]: "Reject",
  [ORDER_STATUS.EXPIRED]: "Cancel",
  [ORDER_STATUS.ON_GOING]: "Ongoing",
  [ORDER_STATUS.COMPLETED]: "Complete",
  [ORDER_STATUS.USER_PICKED_UP]: "User Pick Up",
  [ORDER_STATUS.PREPARED]: "Prepared",
  [ORDER_STATUS.PAID]: "Paid",
  [ORDER_STATUS.REFUND_REJECTED]: "Refund refused",
};

export enum ORDER_PAYMENT_STATUS {
  PENDING = 0,
  CONFIRMED = 1,
  CANCELLED = 4,
  REFUNDING = 5,

  REFUNDED = 6,
  SUCCEEDED = 7,
  SETTLED = 8,
  WAITING_FOR_PAYMENT = 9,
}

export enum DELIVERY_TYPES {
  STANDARD = 0,
  EXPRESS = 1,
  PRIORITY = 3,
  SAME_DAY = 4,
  OVERNIGHT = 5,
}
