const ENV = {
  NEXT_PUBLIC_CHAIN_ID: process.env.NEXT_PUBLIC_CHAIN_ID,
  NEXT_PUBLIC_NETWORK_NAME: process.env.NEXT_PUBLIC_NETWORK_NAME,
  NEXT_PUBLIC_BLOCK_EXPLORER_URL: process.env.NEXT_PUBLIC_BLOCK_EXPLORER_URL,
  NEXT_PUBLIC_BSC_RPC_URL: process.env.NEXT_PUBLIC_BSC_RPC_URL,
  NEXT_PUBLIC_BSC_CHAIN_ID_HEX: process.env.NEXT_PUBLIC_BSC_CHAIN_ID_HEX,
  NEXT_PUBLIC_PROJECT_ID: process.env.NEXT_PUBLIC_PROJECT_ID,
  NEXT_PUBLIC_MINT_CONTRACT: process.env.NEXT_PUBLIC_MINT_CONTRACT,
  NEXT_PUBLIC_PUBLIC_KEY: process.env.NEXT_PUBLIC_PUBLIC_KEY,
  NEXT_PUBLIC_API_BASE_URL: process.env.NEXT_PUBLIC_API_BASE_URL,
  NEXT_PUBLIC_MESSAGES_SIGN: process.env.NEXT_PUBLIC_MESSAGES_SIGN,
};

export const {
  NEXT_PUBLIC_MESSAGES_SIGN,
  NEXT_PUBLIC_CHAIN_ID,
  NEXT_PUBLIC_NETWORK_NAME,
  NEXT_PUBLIC_BLOCK_EXPLORER_URL,
  NEXT_PUBLIC_BSC_RPC_URL,
  NEXT_PUBLIC_BSC_CHAIN_ID_HEX,
  NEXT_PUBLIC_PROJECT_ID,
  NEXT_PUBLIC_MINT_CONTRACT,
  NEXT_PUBLIC_PUBLIC_KEY,
  NEXT_PUBLIC_API_BASE_URL,
} = ENV;
