{{- $service:= .Values.service -}}
{{- $global:= .Values.global -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $service.name }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    
spec:
  type: {{ $service.type }}
  ports:
  - port: {{ $service.externalPort }}
    targetPort: {{ $service.internalPort }}
    protocol: TCP
    name: {{ $service.name }}
  selector:
    app: {{ $global.app }}